// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/transport/controller/grpc/food/proto/food.proto

package food

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос: список ID блюд
type GetFoodsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodIds       []string               `protobuf:"bytes,1,rep,name=food_ids,json=foodIds,proto3" json:"food_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodsByIdsRequest) Reset() {
	*x = GetFoodsByIdsRequest{}
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodsByIdsRequest) ProtoMessage() {}

func (x *GetFoodsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetFoodsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_food_proto_food_proto_rawDescGZIP(), []int{0}
}

func (x *GetFoodsByIdsRequest) GetFoodIds() []string {
	if x != nil {
		return x.FoodIds
	}
	return nil
}

// Ответ: список блюд
type GetFoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FoodDTO             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodsResponse) Reset() {
	*x = GetFoodsResponse{}
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodsResponse) ProtoMessage() {}

func (x *GetFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodsResponse.ProtoReflect.Descriptor instead.
func (*GetFoodsResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_food_proto_food_proto_rawDescGZIP(), []int{1}
}

func (x *GetFoodsResponse) GetData() []*FoodDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

// Модель блюда
type FoodDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	AvgPoint      float32                `protobuf:"fixed32,6,opt,name=avg_point,json=avgPoint,proto3" json:"avg_point,omitempty"`
	CommentQty    int64                  `protobuf:"varint,7,opt,name=comment_qty,json=commentQty,proto3" json:"comment_qty,omitempty"`
	CategoryId    string                 `protobuf:"bytes,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,9,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodDTO) Reset() {
	*x = FoodDTO{}
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodDTO) ProtoMessage() {}

func (x *FoodDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodDTO.ProtoReflect.Descriptor instead.
func (*FoodDTO) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_food_proto_food_proto_rawDescGZIP(), []int{2}
}

func (x *FoodDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoodDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FoodDTO) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *FoodDTO) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FoodDTO) GetAvgPoint() float32 {
	if x != nil {
		return x.AvgPoint
	}
	return 0
}

func (x *FoodDTO) GetCommentQty() int64 {
	if x != nil {
		return x.CommentQty
	}
	return 0
}

func (x *FoodDTO) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *FoodDTO) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *FoodDTO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Запрос на обновление блюда
type UpdateFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,5,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Image         string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFoodRequest) Reset() {
	*x = UpdateFoodRequest{}
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodRequest) ProtoMessage() {}

func (x *UpdateFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodRequest.ProtoReflect.Descriptor instead.
func (*UpdateFoodRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_food_proto_food_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFoodRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFoodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFoodRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFoodRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateFoodRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *UpdateFoodRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateFoodRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// Ответ на обновление
type UpdateFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFoodResponse) Reset() {
	*x = UpdateFoodResponse{}
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoodResponse) ProtoMessage() {}

func (x *UpdateFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoodResponse.ProtoReflect.Descriptor instead.
func (*UpdateFoodResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_food_proto_food_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFoodResponse) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

var File_internal_transport_controller_grpc_food_proto_food_proto protoreflect.FileDescriptor

const file_internal_transport_controller_grpc_food_proto_food_proto_rawDesc = "" +
	"\n" +
	"8internal/transport/controller/grpc/food/proto/food.proto\"1\n" +
	"\x14GetFoodsByIdsRequest\x12\x19\n" +
	"\bfood_ids\x18\x01 \x03(\tR\afoodIds\"0\n" +
	"\x10GetFoodsResponse\x12\x1c\n" +
	"\x04data\x18\x01 \x03(\v2\b.FoodDTOR\x04data\"\x97\x02\n" +
	"\aFoodDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1b\n" +
	"\tavg_point\x18\x06 \x01(\x02R\bavgPoint\x12\x1f\n" +
	"\vcomment_qty\x18\a \x01(\x03R\n" +
	"commentQty\x12\x1f\n" +
	"\vcategory_id\x18\b \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rrestaurant_id\x18\t \x01(\tR\frestaurantId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"\xcd\x01\n" +
	"\x11UpdateFoodRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rrestaurant_id\x18\x05 \x01(\tR\frestaurantId\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\"-\n" +
	"\x12UpdateFoodResponse\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId2\x83\x01\n" +
	"\vFoodService\x12;\n" +
	"\rGetFoodsByIds\x12\x15.GetFoodsByIdsRequest\x1a\x11.GetFoodsResponse\"\x00\x127\n" +
	"\n" +
	"UpdateFood\x12\x12.UpdateFoodRequest\x1a\x13.UpdateFoodResponse\"\x00BXZVgithub.com/AlexSamarskii/delivery_service/internal/transport/controller/grpc/food;foodb\x06proto3"

var (
	file_internal_transport_controller_grpc_food_proto_food_proto_rawDescOnce sync.Once
	file_internal_transport_controller_grpc_food_proto_food_proto_rawDescData []byte
)

func file_internal_transport_controller_grpc_food_proto_food_proto_rawDescGZIP() []byte {
	file_internal_transport_controller_grpc_food_proto_food_proto_rawDescOnce.Do(func() {
		file_internal_transport_controller_grpc_food_proto_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_controller_grpc_food_proto_food_proto_rawDesc), len(file_internal_transport_controller_grpc_food_proto_food_proto_rawDesc)))
	})
	return file_internal_transport_controller_grpc_food_proto_food_proto_rawDescData
}

var file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_transport_controller_grpc_food_proto_food_proto_goTypes = []any{
	(*GetFoodsByIdsRequest)(nil), // 0: GetFoodsByIdsRequest
	(*GetFoodsResponse)(nil),     // 1: GetFoodsResponse
	(*FoodDTO)(nil),              // 2: FoodDTO
	(*UpdateFoodRequest)(nil),    // 3: UpdateFoodRequest
	(*UpdateFoodResponse)(nil),   // 4: UpdateFoodResponse
}
var file_internal_transport_controller_grpc_food_proto_food_proto_depIdxs = []int32{
	2, // 0: GetFoodsResponse.data:type_name -> FoodDTO
	0, // 1: FoodService.GetFoodsByIds:input_type -> GetFoodsByIdsRequest
	3, // 2: FoodService.UpdateFood:input_type -> UpdateFoodRequest
	1, // 3: FoodService.GetFoodsByIds:output_type -> GetFoodsResponse
	4, // 4: FoodService.UpdateFood:output_type -> UpdateFoodResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_transport_controller_grpc_food_proto_food_proto_init() }
func file_internal_transport_controller_grpc_food_proto_food_proto_init() {
	if File_internal_transport_controller_grpc_food_proto_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_controller_grpc_food_proto_food_proto_rawDesc), len(file_internal_transport_controller_grpc_food_proto_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_controller_grpc_food_proto_food_proto_goTypes,
		DependencyIndexes: file_internal_transport_controller_grpc_food_proto_food_proto_depIdxs,
		MessageInfos:      file_internal_transport_controller_grpc_food_proto_food_proto_msgTypes,
	}.Build()
	File_internal_transport_controller_grpc_food_proto_food_proto = out.File
	file_internal_transport_controller_grpc_food_proto_food_proto_goTypes = nil
	file_internal_transport_controller_grpc_food_proto_food_proto_depIdxs = nil
}
