// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/transport/controller/grpc/category/proto/category.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос: список ID категорий
type GetCategoriesByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesByIdsRequest) Reset() {
	*x = GetCategoriesByIdsRequest{}
	mi := &file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesByIdsRequest) ProtoMessage() {}

func (x *GetCategoriesByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesByIdsRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_category_proto_category_proto_rawDescGZIP(), []int{0}
}

func (x *GetCategoriesByIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Ответ: список категорий
type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CategoryDTO         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_category_proto_category_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoriesResponse) GetData() []*CategoryDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

// Модель категории
type CategoryDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryDTO) Reset() {
	*x = CategoryDTO{}
	mi := &file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryDTO) ProtoMessage() {}

func (x *CategoryDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryDTO.ProtoReflect.Descriptor instead.
func (*CategoryDTO) Descriptor() ([]byte, []int) {
	return file_internal_transport_controller_grpc_category_proto_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryDTO) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryDTO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_transport_controller_grpc_category_proto_category_proto protoreflect.FileDescriptor

const file_internal_transport_controller_grpc_category_proto_category_proto_rawDesc = "" +
	"\n" +
	"@internal/transport/controller/grpc/category/proto/category.proto\x12\bcategory\"-\n" +
	"\x19GetCategoriesByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"B\n" +
	"\x15GetCategoriesResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.category.CategoryDTOR\x04data\"\x7f\n" +
	"\vCategoryDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2m\n" +
	"\x0fCategoryService\x12Z\n" +
	"\x12GetCategoriesByIds\x12#.category.GetCategoriesByIdsRequest\x1a\x1f.category.GetCategoriesResponseB`Z^github.com/AlexSamarskii/delivery_service/internal/transport/controller/grpc/category;categoryb\x06proto3"

var (
	file_internal_transport_controller_grpc_category_proto_category_proto_rawDescOnce sync.Once
	file_internal_transport_controller_grpc_category_proto_category_proto_rawDescData []byte
)

func file_internal_transport_controller_grpc_category_proto_category_proto_rawDescGZIP() []byte {
	file_internal_transport_controller_grpc_category_proto_category_proto_rawDescOnce.Do(func() {
		file_internal_transport_controller_grpc_category_proto_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_controller_grpc_category_proto_category_proto_rawDesc), len(file_internal_transport_controller_grpc_category_proto_category_proto_rawDesc)))
	})
	return file_internal_transport_controller_grpc_category_proto_category_proto_rawDescData
}

var file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_transport_controller_grpc_category_proto_category_proto_goTypes = []any{
	(*GetCategoriesByIdsRequest)(nil), // 0: category.GetCategoriesByIdsRequest
	(*GetCategoriesResponse)(nil),     // 1: category.GetCategoriesResponse
	(*CategoryDTO)(nil),               // 2: category.CategoryDTO
}
var file_internal_transport_controller_grpc_category_proto_category_proto_depIdxs = []int32{
	2, // 0: category.GetCategoriesResponse.data:type_name -> category.CategoryDTO
	0, // 1: category.CategoryService.GetCategoriesByIds:input_type -> category.GetCategoriesByIdsRequest
	1, // 2: category.CategoryService.GetCategoriesByIds:output_type -> category.GetCategoriesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_transport_controller_grpc_category_proto_category_proto_init() }
func file_internal_transport_controller_grpc_category_proto_category_proto_init() {
	if File_internal_transport_controller_grpc_category_proto_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_controller_grpc_category_proto_category_proto_rawDesc), len(file_internal_transport_controller_grpc_category_proto_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_controller_grpc_category_proto_category_proto_goTypes,
		DependencyIndexes: file_internal_transport_controller_grpc_category_proto_category_proto_depIdxs,
		MessageInfos:      file_internal_transport_controller_grpc_category_proto_category_proto_msgTypes,
	}.Build()
	File_internal_transport_controller_grpc_category_proto_category_proto = out.File
	file_internal_transport_controller_grpc_category_proto_category_proto_goTypes = nil
	file_internal_transport_controller_grpc_category_proto_category_proto_depIdxs = nil
}
